Update office2019activation

diff --git a/office2019activation b/office2019activation
--- a/office2019activation
+++ b/office2019activation
@@ -1,38 +1,19 @@
-# Activate Office 2019/2021 using a 3rd party KMS server
-
-# https://docs.microsoft.com/en-us/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office
-<#
-	ProPlus2021VL
-	Standard2021VL
-	ProPlus2019VL
-	Standard2019VL
-#>
-$Items = @((Get-ChildItem -Path "$env:ProgramFiles\Microsoft Office\root\Licenses16" | Where-Object -FilterScript {$_.FullName -match "Standard2021VL"}).FullName)
-foreach ($Item in $Items)
-{
-	cscript "$env:ProgramFiles\Microsoft Office\Office16\ospp.vbs" /inslic:"$Item" //nologo
-}
-
-# Get the last 5 characters of installed product key to remove it
-if ($null -ne ((cscript "$env:ProgramFiles\Microsoft Office\Office16\ospp.vbs" /dstatus | Select-String -Pattern "Last 5" -SimpleMatch | Out-String).Replace("Last 5 characters of installed product key: ", "").Trim()))
-{
-	$KeyToRemove = (cscript "$env:ProgramFiles\Microsoft Office\Office16\ospp.vbs" /dstatus | Select-String -Pattern "Last 5" -SimpleMatch | Out-String).Replace("Last 5 characters of installed product key: ", "").Trim()
-}
-# Set a KMS port with a user-provided port number. The default port number is 1688
-cscript "$env:ProgramFiles\Microsoft Office\Office16\ospp.vbs" /setprt:1688 //nologo
-# Uninstall an installed product key with the last five digits of the product key to uninstall (as displayed by the /dstatus option)
-cscript "$env:ProgramFiles\Microsoft Office\Office16\ospp.vbs" /unpkey:"$KeyToRemove" //nologo
-
-# https://docs.microsoft.com/en-us/deployoffice/vlactivation/gvlks
-# Office Professional Plus 2019: NMMKJ-6RK4F-KMJVX-8D9MJ-6MWKP
-# Office Standard 2019: 6NWWJ-YQWMR-QKGCB-6TMB3-9D9HK
-# Office Professional Plus 2021: FXYTK-NJJ8C-GB6DW-3DYQT-6F7TH 
-# Office Standard 2021: KDX7X-BNVR8-TXXGX-4Q7Y8-78VT3
-cscript "$env:ProgramFiles\Microsoft Office\Office16\ospp.vbs" /inpkey:NMMKJ-6RK4F-KMJVX-8D9MJ-6MWKP //nologo
-
-# Set the specific DNS domain in which all KMS SRV records can be found. This setting has no effect if the specific single KMS host name is set by the /sethst option
-# https://moe.best/kms.html
-cscript $env:SystemRoot\System32\slmgr.vbs /skms kms.loli.best //nologo
-cscript $env:SystemRoot\System32\slmgr.vbs /ato //nologo
-# Activate installed Office product keys
-cscript "$env:ProgramFiles\Microsoft Office\Office16\ospp.vbs" /act //nologo
+@echo off
+title Activate Microsoft Office 2019 (ALL versions) for FREE - MSGuides.com&cls&echo =====================================================================================&echo #Project: Activating Microsoft software products for FREE without additional software&echo =====================================================================================&echo.&echo #Supported products:&echo - Microsoft Office Standard 2019&echo - Microsoft Office Professional Plus 2019&echo.&echo.&(if exist "%ProgramFiles%\Microsoft Office\Office16\ospp.vbs" cd /d "%ProgramFiles%\Microsoft Office\Office16")&(if exist "%ProgramFiles(x86)%\Microsoft Office\Office16\ospp.vbs" cd /d "%ProgramFiles(x86)%\Microsoft Office\Office16")&(for /f %%x in ('dir /b ..\root\Licenses16\ProPlus2019VL*.xrm-ms') do cscript ospp.vbs /inslic:"..\root\Licenses16\%%x" >nul)&(for /f %%x in ('dir /b ..\root\Licenses16\ProPlus2019VL*.xrm-ms') do cscript ospp.vbs /inslic:"..\root\Licenses16\%%x" >nul)&echo.&echo ============================================================================&echo Activating your Office...&cscript //nologo slmgr.vbs /ckms >nul&cscript //nologo ospp.vbs /setprt:1688 >nul&cscript //nologo ospp.vbs /unpkey:6MWKP >nul&set i=1&cscript //nologo ospp.vbs /inpkey:NMMKJ-6RK4F-KMJVX-8D9MJ-6MWKP >nul||goto notsupported
+:skms
+if %i% GTR 10 goto busy
+if %i% EQU 1 set KMS=kms7.MSGuides.com
+if %i% EQU 2 set KMS=e8.us.to
+if %i% EQU 3 set KMS=e9.us.to
+if %i% GTR 3 goto ato
+cscript //nologo ospp.vbs /sethst:%KMS% >nul
+:ato
+echo ============================================================================&echo.&echo.&cscript //nologo ospp.vbs /act | find /i "successful" && (echo.&echo ============================================================================&echo.&echo #My official blog: MSGuides.com&echo.&echo #How it works: bit.ly/kms-server&echo.&echo #Please feel free to contact me at msguides.com@gmail.com if you have any questions or concerns.&echo.&echo #Please consider supporting this project: donate.msguides.com&echo #Your support is helping me keep my servers running 24/7!&echo.&echo ============================================================================&choice /n /c /m & if errorlevel 2 exit) || (echo The connection to my KMS server failed! Trying to connect to another one... & echo Please wait... & echo. & echo. & set /a i+=1 & goto skms)
+explorer "http://MSGuides.com"&goto halt
+:notsupported
+echo ============================================================================&echo.&echo Sorry, your version is not supported.&echo.&goto halt
+:busy
+echo ============================================================================&echo.&echo Sorry, the server is busy and can't respond to your request. Please try again.&echo.
+:halt
+pause >nul
+exit
